### ISSUE TITLE
error: the example provided by xiSPEC cannot be used (ncvqnv6pn3c28bkm8jfjnbsv5i_1678176426.log)

### ISSUE THREAD

**Issue by xyx233** [Rappsilber-Laboratory/xi-mzidentml-converter#38]
Hello, today, xiSPEC has been reporting an error, even with the example provided by xiSPEC , there will still be an error of sequence of ncvqnv6pn3c28bkm8jfjnbsv5i_1678176426.log , I sincerely hope that you can help me to solve this problem.

**Comment by lars-kolbowski** [comment]
Thank you for reporting this. I'm looking into it. It seems like there is a problem with reading/writing the files on the server

**Comment by lars-kolbowski** [comment]
ok, it should be working again. I just uploaded the example files: "example.csv" and "example.mzML" and that worked. Could you check if the issue is resolved for you as well?
