### ISSUE TITLE
example.mzML cannot load successfully

### ISSUE THREAD

**Issue by xyx233** [Rappsilber-Laboratory/xi-mzidentml-converter#39]
hello, the peak list file cannot be uploaded successfully, not even the example.mzML, every time the upload progress reaches  82%, the progress bar will be cleared. Could you please check it? Thank you very much.

**Comment by colin-combe** [comment]
this is on the spectrumviewer.org website?

**Comment by xyx233** [comment]
> hello, the peak list file cannot be uploaded successfully, not even the example.mzML, every time the upload progress reaches 82%, the progress bar will be cleared. Could you please check it? Thank you very much.

It's a problem from xiSPEC.

**Comment by colin-combe** [comment]
ok, thanks (we have more than one thing using this repo)

**Comment by lars-kolbowski** [comment]
The example can now be uploaded again. 
The server keeps running out of disk space. Can you please provide me with details about the files you are trying to upload (name, file size)? Are you trying to upload peak list files that are very large?

**Comment by xyx233** [comment]
> The example can now be uploaded again. The server keeps running out of disk space. Can you please provide me with details about the files you are trying to upload (name, file size)? Are you trying to upload peak list files that are very large?

the file name that I just uploaded is called "20221019-BSA-1.mgf" and is 278,739KB in size.

**Comment by xyx233** [comment]
> The example can now be uploaded again. The server keeps running out of disk space. Can you please provide me with details about the files you are trying to upload (name, file size)? Are you trying to upload peak list files that are very large?

my files can be uploaded successfully now, thank you so much!❤
