### ISSUE TITLE
xiSPEC Cannot work

### ISSUE THREAD

**Issue by xyx233** [Rappsilber-Laboratory/xi-mzidentml-converter#46]
Dear xiSPEC Manager, Every time the mgf file was uploaded to the xiSPEC, the progress bar was very unstable. When the progress bar reaches 100%, it would return 0%. Can you check it? Thank you so much!

**Comment by colin-combe** [comment]
just to be clear, which web site are you using? 
https://spectrumviewer.org/ or https://xiview.org/ ?

**Comment by colin-combe** [comment]
(theres work being done on xiview.org at moment... its in a state of flux)

**Comment by xyx233** [comment]
The URL used was https://spectrumviewer.org/. The mgf data cannot be uploaded successfully.

**Comment by colin-combe** [comment]
I don't know if https://spectrumviewer.org/ is maintained any longer. Perhaps not. The person that was doing that has left the lab.

You may be able to achieve the same result (or similar) at xiview.org... but there's some work being done on that server at the moment, as i said.

I will update this issue to let you know when xiview.org is stable again. (Or if i hear anything about the maintenance of spectrumviewer.org)

**Comment by xyx233** [comment]
Thank you so much for your notice, I am looking forward to the steady operation of xiview in the future! Thank you very much and wish all the best.

**Comment by colin-combe** [comment]
Hi xyx233 - does this work for you: https://www.rappsilberlab.org/xiSPEC/
?

**Comment by xyx233** [comment]
> Hi xyx233 - does this work for you: https://www.rappsilberlab.org/xiSPEC/ ?

It is work for me again！thank you so much for your help！
