### ISSUE TITLE
After submit the data on xiview, can't see the results

### ISSUE THREAD

**Issue by xyx233** [Rappsilber-Laboratory/xi-mzidentml-converter#71]
submit the data on https://xiview.org/upload.php，the circle of waiting disappeared，can't see the results
![35e93ca239101dcf0422ba42083b4e4](https://github.com/Rappsilber-Laboratory/xi-mzidentml-converter/assets/97680474/7c30b39a-d008-4edd-8a5e-ef3281ae204c)

**Comment by colin-combe** [comment]
ok, thanks, looking into it

**Comment by colin-combe** [comment]
is it working for you now?

**Comment by xyx233** [comment]
> is it working for you now?
Thanks for the reply, I think my question is the same as # 98, I will keep following # 98, thanks again

**Comment by colin-combe** [comment]
can close?

**Comment by xyx233** [comment]
> can close?

Yes, you can close it.
